# Generated by Django 3.2.9 on 2021-11-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=256)),
                ('nickname', models.CharField(max_length=50)),
                ('user_type', models.IntegerField()),
                ('description', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
