# Generated by Django 3.2.9 on 2021-11-26 14:22

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
