<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-11-26 15:03

from django.db import migrations


=======
# Generated by Django 3.2.9 on 2021-11-26 14:22

from django.db import migrations

>>>>>>> 392da801c17a70f69c06746a5b731cb764f41c8b
class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
