# Generated by Django 3.2.9 on 2021-12-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='https://team3-plantit.s3.ap-northeast-2.amazonaws.com/profile/default.png', max_length=100, null=True),
        ),
    ]
