# Generated by Django 3.2.9 on 2021-12-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=256, null='안녕하세요 <django.db.models.fields.CharField>입니다.'),
        ),
    ]
