# Generated by Django 3.2.9 on 2021-11-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide', '0002_remove_pesticide_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticide',
            name='image',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
