# Generated by Django 3.2.9 on 2021-11-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide', '0004_alter_pesticide_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticide',
            name='kind',
            field=models.CharField(max_length=100),
        ),
    ]
