# Generated by Django 3.2.9 on 2021-11-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload_date',
            field=models.CharField(default='2021-11-24', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
