<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-11-27 03:44
=======
# Generated by Django 3.2.9 on 2021-11-27 11:42
>>>>>>> 392da801c17a70f69c06746a5b731cb764f41c8b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('blog', '0005_auto_20211126_1503'),
=======
        ('blog', '0005_auto_20211126_1422'),
>>>>>>> 392da801c17a70f69c06746a5b731cb764f41c8b
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload_date',
            field=models.CharField(default='2021-11-27', max_length=100),
        ),
    ]
