# Generated by Django 3.2.9 on 2021-11-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211126_0820'),
        ('blog', '0006_alter_blog_upload_date'),
    ]

    operations = [
    ]
