# Generated by Django 3.2.9 on 2021-11-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload_date',
            field=models.CharField(default='2021-11-29', max_length=100),
        ),
    ]
