# Generated by Django 3.2.9 on 2021-11-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_merge_20211128_0641'),
        ('blog', '0007_merge_20211128_0855'),
    ]

    operations = [
    ]
