# Generated by Django 3.2.9 on 2021-12-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211126_1503'),
        ('blog', '0007_alter_blog_upload_date'),
        ('blog', '0009_alter_blog_upload_date'),
    ]

    operations = [
    ]
