# Generated by Django 3.2.9 on 2021-12-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_merge_20211130_1450'),
        ('blog', '0011_auto_20211201_1200'),
    ]

    operations = [
    ]
