# Generated by Django 3.2.9 on 2021-12-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_merge_20211207_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload_date',
            field=models.CharField(default='2021-12-07', max_length=100),
        ),
    ]
