# Generated by Django 3.2.9 on 2021-11-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'crop',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('symptom', models.TextField()),
                ('cause', models.TextField()),
                ('prevention', models.JSONField()),
                ('pesticides', models.JSONField()),
                ('crops_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.crop')),
            ],
            options={
                'db_table': 'disease',
            },
        ),
    ]
