# Generated by Django 3.2.9 on 2021-11-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='crops_id',
            new_name='crops',
        ),
    ]
